image: continuumio/miniconda3:latest

stages:
  - test

variables:
  PYVERSION: "3.8"
  SKLLVERSION: "4.0.1"
  MPLBACKEND: "Agg"
  BINDIR: "/root/skllenv/bin"
  TESTDIR: "/root/skllcode"

# set up the basic job to run only for pull requests
.runtests:
  only:
    - external_pull_requests
  before_script:
    - mkdir /root/skllcode
    - cd /root/skllcode
    - git init
    - git remote add -f origin https://github.com/EducationalTestingService/skll.git
    - git config core.sparsecheckout true
    - echo "tests/*" > .git/info/sparse-checkout
    - echo "examples/*" >> .git/info/sparse-checkout
    - git pull --depth=1 origin main
    - "conda create --prefix /root/skllenv python=${PYVERSION} --yes --quiet"
    - "/root/skllenv/bin/pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple skll==${SKLLVERSION} nose2"
  script:
    - "TESTDIR=/root/skllcode /root/skllenv/bin/nose2 -s /root/skllcode/tests --plugin nose2.plugins.junitxml --junit-xml ${TESTFILES}"

# first set of test files
testset1:
  extends: ".runtests"
  variables:
    TESTFILES: "test_featureset test_commandline_utils test_custom_metrics test_voting_learners_api_5"
  stage: "test"

# second set of test files
testset2:
  extends: ".runtests"
  variables:
    TESTFILES: "test_output test_voting_learners_api_4"
  stage: "test"

# third set of test files
testset3:
  extends: ".runtests"
  variables:
    TESTFILES: "test_regression test_voting_learners_api_2"
  stage: "test"

# fourth set of test files
testset4:
  extends: ".runtests"
  variables:
    TESTFILES: "test_input test_preprocessing test_metrics test_custom_learner test_logging_utils test_examples test_voting_learners_api_1 test_voting_learners_expts_1"
  stage: "test"

# fifth set of test files
testset5:
  extends: ".runtests"
  variables:
    TESTFILES: "test_classification test_cv test_ablation test_voting_learners_expts_4"
  stage: "test"

# sixth set of test files
testset6:
  extends: ".runtests"
  variables:
    TESTFILES: "test_voting_learners_api_3 test_voting_learners_expts_2 test_voting_learners_expts_3 test_voting_learners_expts_5"
  stage: "test"
